  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-serverless-http-1.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    QuarkusServerlessHttpNative:
      Type: AWS::Serverless::Function
      Properties:
        Handler: not.used.in.provided.runtimei
        Runtime: provided.al2023
        #If you don't want to build for ARM64 comment 'Architectures'
        Architectures:
          - arm64
        CodeUri: target/function.zip
        MemorySize: 128
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
            OIDC_AUTH_SERVER_URL: !Sub "{{resolve:ssm:/hello-world-quarkus/OIDC_AUTH_SERVER_URL}}"
            OIDC_CLIENT_ID: !Sub "{{resolve:ssm:/hello-world-quarkus/OIDC_CLIENT_ID}}"
            COGNITO_USER_POOL_ID: !Sub "{{resolve:ssm:/hello-world-quarkus/COGNITO_USER_POOL_ID}}"
        Events:
          HttpApiEvent:
            Type: HttpApi

  Outputs:
    QuarkusServerlessHttpNativeApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: QuarkusServerlessHttpNativeApi
