version = 0.1
[default.deploy.parameters]
stack_name = "hello-world-quarkus"
resolve_s3 = true
s3_prefix = "hello-world-quarkus"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
